# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/IP_Design3_Q3_CF.xdc

# Block Designs: bd/design_IP_design3_Q3/design_IP_design3_Q3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_design3_Q3 || ORIG_REF_NAME==design_IP_design3_Q3} -quiet] -quiet

# IP: bd/design_IP_design3_Q3/ip/design_IP_design3_Q3_blk_mem_gen_0_0/design_IP_design3_Q3_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_design3_Q3_blk_mem_gen_0_0 || ORIG_REF_NAME==design_IP_design3_Q3_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_IP_design3_Q3/ip/design_IP_design3_Q3_design_EX3_1and2_0_0/design_IP_design3_Q3_design_EX3_1and2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_design3_Q3_design_EX3_1and2_0_0 || ORIG_REF_NAME==design_IP_design3_Q3_design_EX3_1and2_0_0} -quiet] -quiet

# XDC: c:/Users/OmenLaptop/Vivado/IP_design3_Q3/IP_design3_Q3.gen/sources_1/bd/design_IP_design3_Q3/design_IP_design3_Q3_ooc.xdc
