## This file is a general .xdc for the Basys3 rev B board

## Clock signal
#set_property PACKAGE_PIN W5 [get_ports clk]
	#set_property IOSTANDARD LVCMOS33 [get_ports clk]
	#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
#set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
#set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

## Switches
set_property PACKAGE_PIN V17 [get_ports {Addr[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Addr[0]}]
set_property PACKAGE_PIN V16 [get_ports {Addr[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Addr[1]}]
set_property PACKAGE_PIN W16 [get_ports {Addr[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Addr[2]}]	
set_property PACKAGE_PIN W17 [get_ports {Addr[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {Addr[3]}]
	
set_property PACKAGE_PIN W15 [get_ports {S}]
	set_property IOSTANDARD LVCMOS33 [get_ports {S}]
	
#set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
#set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
#set_property PACKAGE_PIN T2 [get_ports {sw[10]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[10]}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
#set_property PACKAGE_PIN U1 [get_ports {sw[13]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[13]}]
#set_property PACKAGE_PIN T1 [get_ports {sw[14]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[14]}]
#set_property PACKAGE_PIN R2 [get_ports {sw[15]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {mux_out[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[0]}]
set_property PACKAGE_PIN E19 [get_ports {mux_out[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[1]}]
set_property PACKAGE_PIN U19 [get_ports {mux_out[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[2]}]
set_property PACKAGE_PIN V19 [get_ports {mux_out[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[3]}]
set_property PACKAGE_PIN W18 [get_ports {mux_out[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[4]}]
set_property PACKAGE_PIN U15 [get_ports {mux_out[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[5]}]
set_property PACKAGE_PIN U14 [get_ports {mux_out[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {mux_out[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[7]}]
set_property PACKAGE_PIN V13 [get_ports {mux_out[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[8]}]
set_property PACKAGE_PIN V3 [get_ports {mux_out[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[9]}]
set_property PACKAGE_PIN W3 [get_ports {mux_out[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[10]}]
set_property PACKAGE_PIN U3 [get_ports {mux_out[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[11]}]
set_property PACKAGE_PIN P3 [get_ports {mux_out[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[12]}]
set_property PACKAGE_PIN N3 [get_ports {mux_out[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {mux_out[13]}]
#set_property PACKAGE_PIN P1 [get_ports {led[14]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
#set_property PACKAGE_PIN L1 [get_ports {led[15]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]


## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
