@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 19 17:04:24 -0400 2024
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim test_design_IP_design3_Q3_behav -key {Behavioral:sim_1:Functional:test_design_IP_design3_Q3} -tclbatch test_design_IP_design3_Q3.tcl -protoinst "protoinst_files/design_IP_design3_Q3.protoinst" -view C:/Users/OmenLaptop/Vivado/IP_design3_Q3/IP_design3_Q3.srcs/sim_1/imports/OmenLaptop/Vivado/IP_design3_Q3/test_design_IP_design3_Q3_behav.wcfg -log simulate.log"
call xsim  test_design_IP_design3_Q3_behav -key {Behavioral:sim_1:Functional:test_design_IP_design3_Q3} -tclbatch test_design_IP_design3_Q3.tcl -protoinst "protoinst_files/design_IP_design3_Q3.protoinst" -view C:/Users/OmenLaptop/Vivado/IP_design3_Q3/IP_design3_Q3.srcs/sim_1/imports/OmenLaptop/Vivado/IP_design3_Q3/test_design_IP_design3_Q3_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
